#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
# autospec version: v20
# autospec commit: f35655a
#
Name     : cyme
Version  : 2.0.0
Release  : 3
URL      : https://github.com/tuna-f1sh/cyme/archive/refs/tags/v2.0.0.tar.gz
Source0  : https://github.com/tuna-f1sh/cyme/archive/refs/tags/v2.0.0.tar.gz
Source1  : http://localhost/cgit/vendor/cyme/snapshot/cyme-2024-10-22-15-25-41.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 GPL-2.0 GPL-3.0 ICU LGPL-2.1 MIT MPL-2.0-no-copyleft-exception Unicode-DFS-2016 Unlicense
Requires: cyme-license = %{version}-%{release}
BuildRequires : jq
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
```bash
o
o   /---o
/---/---o
o---/
\---\---o
o   \---o
o
```
# Cyme
[![Crates.io](https://img.shields.io/crates/v/cyme?style=flat-square)](https://crates.io/crates/cyme)
[![docs.rs](https://img.shields.io/docsrs/cyme?style=flat-square)](https://docs.rs/cyme/latest/cyme/)

%package license
Summary: license components for the cyme package.
Group: Default

%description license
license components for the cyme package.


%prep
%setup -q -n cyme-2.0.0
cd %{_builddir}
tar xf %{_sourcedir}/cyme-2024-10-22-15-25-41.tar.gz
cd %{_builddir}/cyme-2.0.0
mkdir -p ./vendor
cp -r %{_builddir}/cyme-2024-10-22-15-25-41/* %{_builddir}/cyme-2.0.0/./vendor
%patch -P 1 -p1
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/tuna-f1sh/nusb?branch=cyme"]
git = "https://github.com/tuna-f1sh/nusb"
branch = "cyme"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
mkdir -p %{buildroot}/usr/share/package-licenses/cyme
cp %{_builddir}/cyme-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/cyme/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/cyme/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/cyme/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/android-tzdata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/db8bf4070b91bbabe0f14d1c15f0be86793fab6a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/android-tzdata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/2c87153926f8a458cffc9a435e15571ba721c2fa || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/android_system_properties/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/a8ab3e6caa5e7af0ec9235d5db800ace830c0a38 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/android_system_properties/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ac0bf7546a377351144d930c5e31eff058fe4e8f || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle-wincon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle-wincon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/33dbd2d99ad231460bbb01812a52c85e577bd9ba || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/assert-json-diff/LICENSE %{buildroot}/usr/share/package-licenses/cyme/6f037946f91c8485854b4db19722c14f1594c542 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/atomic-polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/atomic-polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/6453ff68dee219f5547e204433faa3eccc976142 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/atomic-waker/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/atomic-waker/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/atomic-waker/LICENSE-THIRD-PARTY %{buildroot}/usr/share/package-licenses/cyme/709be9d07c00197f2e96593f4cd84f975c4e9f5f || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/bumpalo/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/bumpalo/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/0a1e89ac22450cb0311baa2613bc21b7131b321f || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/byteorder/COPYING %{buildroot}/usr/share/package-licenses/cyme/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/cyme/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/chrono/LICENSE.txt %{buildroot}/usr/share/package-licenses/cyme/c145b1a607ecf06aed81f1d04a65c2e43dffdc63 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_complete/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_complete/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_mangen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/clap_mangen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/18475316845fb3cc66bbe9d9f0cb6e86142afea2 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/colored/LICENSE %{buildroot}/usr/share/package-licenses/cyme/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/core-foundation-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/core-foundation-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/core-foundation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/core-foundation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/critical-section/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/critical-section/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/913147ebdffe289d9f0bd78cbd08c5ccf9a5136b || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/darling/LICENSE %{buildroot}/usr/share/package-licenses/cyme/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/darling_core/LICENSE %{buildroot}/usr/share/package-licenses/cyme/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/darling_macro/LICENSE %{buildroot}/usr/share/package-licenses/cyme/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/deranged/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/deranged/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/diff/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/diff/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/0db0557c9a1561fa3aa6693747121458bf7ddfcd || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/dirs-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/43a3a49bd7af636c923a5ae475395b8e29320529 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/dirs-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/cf762fa3609793d5639ba9e1cbd254db276f50d3 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/dirs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/43a3a49bd7af636c923a5ae475395b8e29320529 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/dirs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/cf762fa3609793d5639ba9e1cbd254db276f50d3 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/fnv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/fnv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/futures-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/futures-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/glob/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/glob/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hash32/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hash32/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/744183c4ca46703f4b738aca20e238e11c9a3b12 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/heapless/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/heapless/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/0944b87279bcbe1938bebeb62f2c15eb9f053a29 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/heck-0.4.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/heck-0.4.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/hex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/b916da18877fcec3d37860fe60c1189c447e90b9 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/iana-time-zone-haiku/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/iana-time-zone-haiku/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/iana-time-zone/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/iana-time-zone/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/ident_case/LICENSE %{buildroot}/usr/share/package-licenses/cyme/218fc8c15534e8840cbff5801582c450c97869ab || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/io-kit-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/fdeb6a285c2ae8b07f910b6de0687ddb60fa7376 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/io-kit-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/2fee89444e88c668e1eb417fb2faa7d230e25f17 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/io-lifetimes/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/io-lifetimes/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/io-lifetimes/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/js-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/js-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/libredox/LICENSE %{buildroot}/usr/share/package-licenses/cyme/f5a7ee42dcefea5415e6af50baca4e0c338bd8fe || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/libudev-sys/LICENSE %{buildroot}/usr/share/package-licenses/cyme/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/libusb1-sys/LICENSE %{buildroot}/usr/share/package-licenses/cyme/6bb421c89a9d305ad0a6061c4c0fd4cceae643c6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/libusb1-sys/libusb/COPYING %{buildroot}/usr/share/package-licenses/cyme/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/linux-raw-sys-0.3.8/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/linux-raw-sys-0.3.8/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/linux-raw-sys-0.3.8/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/mach2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/mach2/LICENSE-BSD %{buildroot}/usr/share/package-licenses/cyme/24b715e62cdfc7753030f43432f6dd229d136c25 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/mach2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/21ecd644e03f61f0d9f8ee3bcc5c207435ff60ca || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/memchr/COPYING %{buildroot}/usr/share/package-licenses/cyme/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/cyme/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/minimal-lexical/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/minimal-lexical/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/minimal-lexical/LICENSE.md %{buildroot}/usr/share/package-licenses/cyme/cd3fe820606ed34ac2591caf068c7cabd3ab3509 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/nix/LICENSE %{buildroot}/usr/share/package-licenses/cyme/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/nom/LICENSE %{buildroot}/usr/share/package-licenses/cyme/27ea6989d4f34b7b944eb884410a31ae20d11686 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/num-conv/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/c54e008a9d57391b98e60b14c8dc524acd7b2df9 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/num-conv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/18f13b198a4a6248c4ce96a0f82de708bc68fd0c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/num_threads/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/d7922ed0153e53eb7d63ea3fcae1040472c67679 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/num_threads/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/31e133ad6e12ed607bafa6decc49865e76e2a8e0 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/nusb/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/nusb/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/pci-ids/LICENSE %{buildroot}/usr/share/package-licenses/cyme/ccce14322328a271daccb4d63654b1020861d88f || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/phf/LICENSE %{buildroot}/usr/share/package-licenses/cyme/2198c24a330f5c131a176574306265b89f5c175c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/phf_codegen/LICENSE %{buildroot}/usr/share/package-licenses/cyme/2198c24a330f5c131a176574306265b89f5c175c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/phf_generator/LICENSE %{buildroot}/usr/share/package-licenses/cyme/2198c24a330f5c131a176574306265b89f5c175c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/phf_shared/LICENSE %{buildroot}/usr/share/package-licenses/cyme/2198c24a330f5c131a176574306265b89f5c175c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/powerfmt/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/2ef5dbf415191a7880f5baa5ab1997a807967c13 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/powerfmt/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/5641ab41a62889b9a22161d95f174fc889dd9660 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/cyme/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/cyme/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/cyme/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/redox_users/LICENSE %{buildroot}/usr/share/package-licenses/cyme/c56bd0668edca4d06b6cd881d4d2839da53058cd || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/cyme/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/roff/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/roff/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rusb/LICENSE %{buildroot}/usr/share/package-licenses/cyme/6bb421c89a9d305ad0a6061c4c0fd4cceae643c6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustc_version/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustc_version/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustix-0.37.27/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustix-0.37.27/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustix-0.37.27/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustversion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/rustversion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/cyme/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/semver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/semver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_with/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_with/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_with_macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/serde_with_macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/shlex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/a97a2888bca904918b3b9ec008fde1d6e9905a6d || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/shlex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/64e8197cb5ae680fcf996cc0ac8760e9f1e2e3a6 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/simple_logger/LICENSE %{buildroot}/usr/share/package-licenses/cyme/c71acd443a1bd9ebd408a1d46f95aefc497d63df || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/slab/LICENSE %{buildroot}/usr/share/package-licenses/cyme/96f019e8abadc7a87b330a697504d874a1c06268 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/spin/LICENSE %{buildroot}/usr/share/package-licenses/cyme/42631684b818350022ee962eef0a9592b159d838 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/stable_deref_trait/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/stable_deref_trait/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/f81793ddf50f460d6111fcbc799cab1a804aa000 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/strsim/LICENSE %{buildroot}/usr/share/package-licenses/cyme/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/strum/LICENSE %{buildroot}/usr/share/package-licenses/cyme/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/strum_macros/LICENSE %{buildroot}/usr/share/package-licenses/cyme/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/terminal_size-0.2.6/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/terminal_size-0.2.6/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/e08d1736c80198e1adec92ff27482e7abbc42d86 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/terminal_size/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/terminal_size/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/e08d1736c80198e1adec92ff27482e7abbc42d86 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/time-core/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/time-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/time-macros/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/time-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/time/LICENSE-Apache %{buildroot}/usr/share/package-licenses/cyme/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/time/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/udev/LICENSE %{buildroot}/usr/share/package-licenses/cyme/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/udevrs/LICENSE %{buildroot}/usr/share/package-licenses/cyme/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/cyme/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/cyme/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/usb-ids/LICENSE %{buildroot}/usr/share/package-licenses/cyme/f66f0f1664a10b7efc7d2f3d884d41ac66222788 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/uuid/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/uuid/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/459ceba57b368122a3cb1fd48edea59d1363cad7 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/vcpkg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/f85f58f2b17e35a1c2fd852cd58e5bae165ebea9 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/vcpkg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3ede8a2ceb97cd197183b1a9d7958b57cea01e14 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-macro-support/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-macro-support/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/wasm-bindgen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-core/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-core/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-sys-0.48.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-sys-0.48.0/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-sys-0.52.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-sys-0.52.0/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/cyme/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/cyme/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cyme-2024-10-22-15-25-41/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cyme/03431277c040357c85596083ac918eb591ac04ac
/usr/share/package-licenses/cyme/067f31555f328efb78075174add7db97d98618c6
/usr/share/package-licenses/cyme/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/cyme/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/cyme/0944b87279bcbe1938bebeb62f2c15eb9f053a29
/usr/share/package-licenses/cyme/0a1e89ac22450cb0311baa2613bc21b7131b321f
/usr/share/package-licenses/cyme/0db0557c9a1561fa3aa6693747121458bf7ddfcd
/usr/share/package-licenses/cyme/13f55d9b7b3a769d76eab5d4a096f7ff24a017be
/usr/share/package-licenses/cyme/18475316845fb3cc66bbe9d9f0cb6e86142afea2
/usr/share/package-licenses/cyme/18f13b198a4a6248c4ce96a0f82de708bc68fd0c
/usr/share/package-licenses/cyme/218fc8c15534e8840cbff5801582c450c97869ab
/usr/share/package-licenses/cyme/2198c24a330f5c131a176574306265b89f5c175c
/usr/share/package-licenses/cyme/21ecd644e03f61f0d9f8ee3bcc5c207435ff60ca
/usr/share/package-licenses/cyme/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/cyme/24b715e62cdfc7753030f43432f6dd229d136c25
/usr/share/package-licenses/cyme/27ea6989d4f34b7b944eb884410a31ae20d11686
/usr/share/package-licenses/cyme/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/cyme/2c87153926f8a458cffc9a435e15571ba721c2fa
/usr/share/package-licenses/cyme/2ef5dbf415191a7880f5baa5ab1997a807967c13
/usr/share/package-licenses/cyme/2fee89444e88c668e1eb417fb2faa7d230e25f17
/usr/share/package-licenses/cyme/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/cyme/31e133ad6e12ed607bafa6decc49865e76e2a8e0
/usr/share/package-licenses/cyme/33dbd2d99ad231460bbb01812a52c85e577bd9ba
/usr/share/package-licenses/cyme/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/cyme/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/cyme/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/cyme/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/cyme/3ede8a2ceb97cd197183b1a9d7958b57cea01e14
/usr/share/package-licenses/cyme/42631684b818350022ee962eef0a9592b159d838
/usr/share/package-licenses/cyme/43a3a49bd7af636c923a5ae475395b8e29320529
/usr/share/package-licenses/cyme/459ceba57b368122a3cb1fd48edea59d1363cad7
/usr/share/package-licenses/cyme/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/cyme/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/cyme/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/cyme/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/cyme/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/cyme/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a
/usr/share/package-licenses/cyme/5641ab41a62889b9a22161d95f174fc889dd9660
/usr/share/package-licenses/cyme/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/cyme/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/cyme/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/cyme/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/cyme/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/cyme/6453ff68dee219f5547e204433faa3eccc976142
/usr/share/package-licenses/cyme/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/cyme/64e8197cb5ae680fcf996cc0ac8760e9f1e2e3a6
/usr/share/package-licenses/cyme/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/cyme/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/cyme/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/cyme/6bb421c89a9d305ad0a6061c4c0fd4cceae643c6
/usr/share/package-licenses/cyme/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/cyme/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/cyme/6f037946f91c8485854b4db19722c14f1594c542
/usr/share/package-licenses/cyme/709be9d07c00197f2e96593f4cd84f975c4e9f5f
/usr/share/package-licenses/cyme/744183c4ca46703f4b738aca20e238e11c9a3b12
/usr/share/package-licenses/cyme/75b9500512bb4d24722887e64a982c51e6bdcc4c
/usr/share/package-licenses/cyme/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/cyme/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/cyme/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/cyme/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/cyme/913147ebdffe289d9f0bd78cbd08c5ccf9a5136b
/usr/share/package-licenses/cyme/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/cyme/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/cyme/967573fc64a706430e19b4942fe728870c8182f8
/usr/share/package-licenses/cyme/96f019e8abadc7a87b330a697504d874a1c06268
/usr/share/package-licenses/cyme/9744cedce099f727b327cd9913a1fdc58a7f5599
/usr/share/package-licenses/cyme/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/cyme/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/cyme/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/cyme/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/cyme/a8ab3e6caa5e7af0ec9235d5db800ace830c0a38
/usr/share/package-licenses/cyme/a97a2888bca904918b3b9ec008fde1d6e9905a6d
/usr/share/package-licenses/cyme/ac0bf7546a377351144d930c5e31eff058fe4e8f
/usr/share/package-licenses/cyme/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/cyme/b916da18877fcec3d37860fe60c1189c447e90b9
/usr/share/package-licenses/cyme/c145b1a607ecf06aed81f1d04a65c2e43dffdc63
/usr/share/package-licenses/cyme/c54e008a9d57391b98e60b14c8dc524acd7b2df9
/usr/share/package-licenses/cyme/c56bd0668edca4d06b6cd881d4d2839da53058cd
/usr/share/package-licenses/cyme/c71acd443a1bd9ebd408a1d46f95aefc497d63df
/usr/share/package-licenses/cyme/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/cyme/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/cyme/caeb68c46fa36651acf592771d09de7937926bb3
/usr/share/package-licenses/cyme/cc1662c1ffded2451f1b822c62ec085862bd5816
/usr/share/package-licenses/cyme/cc17a68a18e4a5992a1f67a57c49855b9cfd444c
/usr/share/package-licenses/cyme/ccce14322328a271daccb4d63654b1020861d88f
/usr/share/package-licenses/cyme/cd3fe820606ed34ac2591caf068c7cabd3ab3509
/usr/share/package-licenses/cyme/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/cyme/cf762fa3609793d5639ba9e1cbd254db276f50d3
/usr/share/package-licenses/cyme/d3f4001d9de83a122956c9195d73e2507bf6c533
/usr/share/package-licenses/cyme/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/cyme/d7922ed0153e53eb7d63ea3fcae1040472c67679
/usr/share/package-licenses/cyme/db8bf4070b91bbabe0f14d1c15f0be86793fab6a
/usr/share/package-licenses/cyme/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/cyme/e08d1736c80198e1adec92ff27482e7abbc42d86
/usr/share/package-licenses/cyme/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/cyme/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/cyme/e81567c196622efa36b46c5fd53cde741aaf0993
/usr/share/package-licenses/cyme/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/cyme/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/cyme/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/cyme/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/cyme/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/cyme/f5a7ee42dcefea5415e6af50baca4e0c338bd8fe
/usr/share/package-licenses/cyme/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/cyme/f66f0f1664a10b7efc7d2f3d884d41ac66222788
/usr/share/package-licenses/cyme/f81793ddf50f460d6111fcbc799cab1a804aa000
/usr/share/package-licenses/cyme/f85f58f2b17e35a1c2fd852cd58e5bae165ebea9
/usr/share/package-licenses/cyme/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/cyme/fdeb6a285c2ae8b07f910b6de0687ddb60fa7376
/usr/share/package-licenses/cyme/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/cyme/ff44b187892fcf1cd15a3ca61b498041b28afecc
/usr/share/package-licenses/cyme/ffffe83fef2bd6576c95e851bc81e1f6a641d638
